# Generated by Django 4.2.5 on 2023-09-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nieznane', max_length=100)),
                ('surname', models.CharField(default='Nieznane', max_length=100)),
                ('address', models.CharField(default='Nieznany', max_length=100)),
                ('phone_number', models.CharField(default='Nieznany', max_length=9)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('class_referee', models.CharField(default='Nieznana', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefereeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_finish', models.TimeField()),
                ('number_of_matches', models.PositiveIntegerField()),
                ('possible_distance_match', models.PositiveIntegerField(default=0)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Home.referee')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('class_match', models.CharField(choices=[('IV LIGA', 'IV LIGA'), ('Klasa Okręgowa', 'Klasa Okręgowa'), ('A Klasa', 'A Klasa'), ('B Klasa', 'B Klasa')], max_length=50)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.referee')),
            ],
        ),
    ]
