# Generated by Django 4.2.5 on 2023-09-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_referee_class_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='class_referee',
            field=models.CharField(choices=[('IV LIGA', 'IV LIGA'), ('Klasa Okręgowa', 'Klasa Okręgowa'), ('A Klasa', 'A Klasa'), ('B Klasa', 'B Klasa')], default='B Klasa', max_length=100),
        ),
    ]
