# Generated by Django 4.2.5 on 2023-09-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='email',
            field=models.CharField(default='Nieznany', max_length=100),
        ),
    ]
