# Generated by Django 4.2.5 on 2023-09-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_referee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_sent',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=250),
        ),
    ]
