# Generated by Django 4.2.5 on 2023-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_date_sent_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_sent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_sender',
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
