# Generated by Django 4.2.5 on 2023-10-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_message_recipient_deleted_message_sender_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='data',
        ),
        migrations.AddField(
            model_name='match',
            name='data_match',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_assistant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_referee_assistant1', to='Home.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_assistant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_referee_assistant2', to='Home.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='time_match',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_referee', to='Home.referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='Home.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_visit', to='Home.team'),
        ),
    ]
