# Generated by Django 4.2.5 on 2023-10-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_team_remove_match_data_match_data_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nazwa',
            new_name='name',
        ),
    ]
