# Generated by Django 4.2.5 on 2023-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_referee_class_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeavailability',
            name='vacation',
            field=models.BooleanField(default=False),
        ),
    ]
